name: speed_co
description: A new Flutter project.


publish_to: 'none'


version: 1.0.4+12

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.7
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.9
  conditional_builder_null_safety: ^0.0.6
  easy_localization: ^3.0.1
  dio: ^4.0.6
  fluttertoast: ^8.0.8
  internet_connection_checker: ^0.0.1+4
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  geocoding: ^2.0.2
  carousel_slider: ^4.1.1
  smooth_page_indicator: ^1.0.0+2
  image_picker: ^0.8.6
  url_launcher: ^6.1.7
  audioplayers: ^3.0.1
  permission_handler: ^10.2.0
  flutter_sound: ^9.2.13
  flutter_polyline_points: ^1.0.0
  flutter_launcher_icons: ^0.11.0
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_native_image: ^0.0.6+1
  new_version_plus: ^0.0.9
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  flutter_local_notifications: ^12.0.4
  flutter_html: ^3.0.0-alpha.6
  package_info_plus: ^3.0.3
  path_provider: ^2.0.11
  audio_session: ^0.1.13







dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/langs/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
