// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyDJH96p8tZQL_rCpqfsPUvzOZkFxs0FJsc',
      appId: '1:81927502481:android:ebfe4fd8ec0dbc84b6dd30',
      messagingSenderId: '81927502481',
      projectId: 'speedco-4e2be',
      storageBucket: 'speedco-4e2be.appspot.com',
      androidClientId: '81927502481-pqblulbs586pf4j9sp0kl82tnnmi8kr1.apps.googleusercontent.com',
     // deepLinkURLScheme: 'https://soldoutapp.page.link/'
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyAksXh_KZEThF6LmRNKq5vSbZg8ygu5SVA',
      appId: '1:81927502481:ios:e1b95dd4d22f008fb6dd30',
      messagingSenderId: '81927502481',
      projectId: 'speedco-4e2be',
      storageBucket: 'speedco-4e2be.appspot.com',
      iosClientId: '81927502481-hiipui2ni894slqa6l5mn4o86vk3i5df.apps.googleusercontent.com',
      iosBundleId: 'co.speed-co',
   //   deepLinkURLScheme: 'https://soldoutapp.page.link/'
  );

}
