// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: 'AIzaSyB2YiCpRGyD78-I_eoMAvbqGM1rJMxNpnk',
//       appId: '1:957718880537:android:32d2dcbc36fef94f4ae588',
//       messagingSenderId: '957718880537',
//       projectId: 'wafr-5983d',
//       storageBucket: 'wafr-5983d.appspot.com',
//       androidClientId: '957718880537-8jtfl24fkatib9sk92s30ua4dcprns8b.apps.googleusercontent.com',
//      // deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: 'AIzaSyDbCwmv4KXXQwCrXW_BDzCBiYq4a_nW9zo',
//       appId: '1:957718880537:ios:a95058b27b5c4c434ae588',
//       messagingSenderId: '957718880537',
//       projectId: 'wafr-5983d',
//       storageBucket: 'wafr-5983d.appspot.com',
//       iosClientId: '957718880537-6ijd4fhsj3rr4o0nhb25h4b6pjtq8j7p.apps.googleusercontent.com',
//       iosBundleId: 'com.wafr',
//    //   deepLinkURLScheme: 'https://soldoutapp.page.link/'
//   );
//
// }
